### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by waynebrantley** [s12v/newrelic-elasticsearch#16]
I installed this plug-in via a docker container.  It all works, but on the plug-in page it says there is a newer version of the plugin available.  Perhaps the image was not updated or something?

docker run -d \
    -e NEW_RELIC_LICENSE_KEY=secret  \
    --restart=always \
    --name elasticmonitor \
    --link elasticsearch:elasticsearch \
    s12v/newrelic-elasticsearch

**Comment by s12v** [comment]
@waynebrantley, you're right, I updated the plugin recently, but not the image

**Comment by s12v** [comment]
updated: https://hub.docker.com/r/s12v/newrelic-elasticsearch/builds/b8hik6dobjznbjqd4dohrm9/
thank you
