### ISSUE TITLE
Incorrect reported number of nodes

### ISSUE THREAD

**Issue by jdavisclark** [s12v/newrelic-elasticsearch#31]
The plugin reports a hillarious number of nodes on the overview page. The total seems to be correct elsewhere.

For a 9 node cluster (elastic v1.7.5): ![9 node image](http://i.imgur.com/pruzFPi.png)

For a 1 node cluster (elastic v2.1.0) ![1 node image](http://i.imgur.com/zNDlIIl.png)

**Comment by giubueno** [comment]
I am having the same problem here.

Docs                    Nodes      Max heap used, % Versions  
2.04G documents 5.03 nodes  69.5%                   1.01 versions

**Comment by lucasvilelarodrigues** [comment]
Same problem.

Could you help us?!

Thanks!

**Comment by luchetto81** [comment]
I've the same problem too

**Comment by ayashjorden** [comment]
Me as well:
![selection_015](https://cloud.githubusercontent.com/assets/4204371/17527255/4b775d80-5e73-11e6-8dd0-783fc1fe5622.png)

**Comment by mattshep** [comment]
Still seeing this issue using a self-compiled build of `2.2.1-4-g031c8d1`, cluster is 4 nodes total (2 data and 2 master):

![image](https://cloud.githubusercontent.com/assets/6814651/21572732/7fb00168-ce91-11e6-943d-ee212c62ae4d.png)

**Comment by fnash** [comment]
UP

**Comment by s12v** [comment]
@fnash, yeah, awkward issue and we also have it :( Unfortunately not much time to work on the project right now and issue is pretty minor. I'll try to find a moment and look into it.

In the meantime, PRs are welcome ;)

**Comment by nonbeing** [comment]
Same problem here. Otherwise, this is an amazing NR plugin. Thank you for your awesome work!

**Comment by pts-kevinqiu** [comment]
![image](https://cloud.githubusercontent.com/assets/22983808/24817937/878d9da6-1bac-11e7-858b-c06f468a9c60.png)

Same here. I also did a tcpdump on the machine where the plugin is installed to see if the plugin is getting the right response. Looks like the plugin is getting the right number of nodes, and given the unit tests testing the parser, I don't think there's anything wrong with the code. Another proof for the code being correct is that on the nodes page, it does report the right amount of nodes:

![image](https://cloud.githubusercontent.com/assets/22983808/24817989/ae582d52-1bac-11e7-9d69-241ca0f5de19.png)

@s12v This led me to think could it be the case that you accidentally picked the wrong metrics when configuring the overview page of the plugin?

**Comment by s12v** [comment]
@pts-kevinqiu, good point. I edited the dashboard, could you please check?

**Comment by pts-kevinqiu** [comment]
@s12v 
![image](https://cloud.githubusercontent.com/assets/22983808/24864276/aa8c6c66-1dd1-11e7-96e2-0d256784c8e6.png)

Confirmed it works as expected now. :+1:

**Comment by fnash** [comment]
Thank you!

**Comment by s12v** [comment]
Thanks!
