### ISSUE TITLE
It works behind http proxy?

### ISSUE THREAD

**Issue by brunodomenici** [s12v/newrelic-elasticsearch#32]
Hi,
I couldn't find any config for http_proxy. Its works behind a proxy?
Thank you.

**Comment by ghost** [comment]
Any luck @brunodomenici ?

**Comment by brunodomenici** [comment]
I was able to configure proxy including "proxy_host" and "proxy_port" on config/newrelic.json.

**Comment by alaviamir** [comment]
Thank you for your prompt response @brunodomenici 
I have tried almost everything at this point but still no luck. 

Do you simply modify the content of "/root/newrelic-npi/plugins/me.snov.newrelic-elasticsearch/newrelic-elasticsearch-plugin-2.3.0/config/newrelic.json" or do you use a different way of configuring the proxy? 

I have tried setting the system proxy and also adding those two properties (proxy_host and proxy_port) to the newrelic.json file mentioned above.

Thanks!

**Comment by ghost** [comment]
Thank you, that did the trick!
