### ISSUE TITLE
Cluster status is missing?

### ISSUE THREAD

**Issue by bbergstrom** [s12v/newrelic-elasticsearch#33]
Cluster status is a really important data point, but I can't find it anywhere in the New Relic dashboard for this plugin.  Ideally, it would alert when red.  Is that implemented and I just can't find it?  If not implemented, could it be added?

**Comment by dbaggott** [comment]
@s12v, As I'm sure you already know, New Relic doesn't natively support boolean metrics but you can work around the problem as discussed here: https://github.com/CafepressDev/newrelic-dropwizard-plugin#implementation-fine-print.

"IsRed" and "IsYellow" pseudo-boolean metrics would allow alerting on either one of those states.  If that sounds reasonable, I can put together a PR...

**Comment by s12v** [comment]
@dbaggott, sounds good to me!

**Comment by dbaggott** [comment]
Ok, I'll get something together this week or early next...  Time permitting, I'll tackle some of the other issues.  Do you want separate PRs per issue or is it OK to tackle multiple issues in the same PR?

**Comment by s12v** [comment]
@dbaggott, separate PRs might speed things up, but at the end both are fine

**Comment by s12v** [comment]
Published 2.2.1
