### ISSUE TITLE
Customizable Cluster Names

### ISSUE THREAD

**Issue by svperfecta** [s12v/newrelic-elasticsearch#4]
Hey @s12v - Congrats! This is the only plugin for NewRelic that seems to work, and it works great!  One question... We monitor about a dozen different logstash instances, all of which have a cluster named "logstash".  They are kept logically separate because they are each on different subnets.  Is there any way to tell the monitoring agent to send a different name to NewRelic for each cluster?

**Comment by s12v** [comment]
@genexp, please upgrade the plugin to 1.4.0, there's a new configuration template:

``` json
{
  "agents": [
    {
      "host" : "localhost",
      "port" : 9200,
      "_name": "Optional. By default loaded from elasticsearch. Rename to 'name' if you need to customize it"
    }
  ]
}
```

Rename `_name` to `name` and it should work

**Comment by svperfecta** [comment]
Wow, awesome!  Great plugin :)
