### ISSUE TITLE
plugin alerting for nodes is in reverse

### ISSUE THREAD

**Issue by danielkraaijbax** [s12v/newrelic-elasticsearch#40]
Hello,

We have a small cluster running of 3 nodes and i wanted to add alerting when 1 or more nodes are down. However the alerting order seems to be in reverse. Am i missing something?

<img width="272" alt="elasticsearch-elarting" src="https://cloud.githubusercontent.com/assets/6949841/16196610/f3d22416-36fe-11e6-9a22-d75cac2ce058.png">

**Comment by s12v** [comment]
@danielkraaijbax, there's no "Number of nodes down" metric, mainly because plugin doesn't know the desired number of nodes.

Looks like this metric is current number of nodes, and alerting wouldn't work in this way.

**Comment by danielkraaijbax** [comment]
@s12v Yes, that much i understood ;) 

Can you explain to me where this alert is for then? 

If i understand correctly then this alert will fire if the number of nodes is getting higher.
eg: If i set the Caution to 2 and Critical to 3 than if a have only 1 node running it would be okay?  
and when our 3 node cluster is fully up-n-running this alert would fire critical?

Thanks for you answer

**Comment by s12v** [comment]
@danielkraaijbax, yes, that's how I understand this. Doesn't make much sense with the number of nodes :)

Good example is JVM heap usage, i.e. >80% warning, >90% critical

**Comment by danielkraaijbax** [comment]
@s12v hahaha, great :) i thought i might have understood this ;)
We will have to figure out another way to monitor the number of nodes running and reporting.

I'll close this issue :)
Thanks for your answers so far.

**Comment by dbaggott** [comment]
@danielkraaijbax -- perhaps you can alert on isYellow and isRed cluster statuses as a proxy for node(s) being down?

**Comment by danielkraaijbax** [comment]
@dbaggott Could you elaborate that? 
One possibility i'm thinking of now is using a Zabbix for monitoring this. Seems like NewRelic is not up to this kind of monitoring. :-(

**Comment by dbaggott** [comment]
@danielkraaijbax, depending on how your cluster is configured, a missing node might result in a yellow cluster status (https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html).

If so, the NR plugin should allow you to alert on that -- it reports a pseudo-boolean metric that is 0 when the cluster is not yellow and 1 when the cluster is yellow.  You can get NR to alert when the metric is greater than some very small value (eg 0.001).  Ditto for the cluster going red.

In practice, most cluster configurations replicate shards back to a green state when a node fails so I'm not super optimistic the suggestion will get you anywhere...  But, regardless, cluster status is still a very good thing to warn/alert on...

**Comment by danielkraaijbax** [comment]
@dbaggott Ah, yes. Good point :-) 

I created in the new Alert system a alert which is working correctly now. Thanks for your help :-)
