### ISSUE TITLE
Cluster Dashboard Nodes and Versions columns incorrect values

### ISSUE THREAD

**Issue by mkolek** [s12v/newrelic-elasticsearch#45]
The Nodes and Versions column randomly displays non whole numbers at times. For example, 6.01 nodes within a cluster or version .999 instead of 1, etc. Some days everything looks good and other days some clusters show this behavior.

**Comment by mkolek** [comment]
![image](https://cloud.githubusercontent.com/assets/7319514/19355034/74084546-912e-11e6-89f4-66c5f557e10f.png)

**Comment by s12v** [comment]
Duplicates https://github.com/s12v/newrelic-elasticsearch/issues/9

I have the same issues. Unfortunately, no solution so far.

**Comment by mkolek** [comment]
Ok - thanks.
