### ISSUE TITLE
Elasticsearch plugin installation

### ISSUE THREAD

**Issue by ipapazov** [s12v/newrelic-elasticsearch#56]
Hi ,

I just want to confirm that to use the elasticsearch New Relic plugin, we need to install it on every elasticsearch master/client/data node?

Cheers,
Hristo

**Comment by s12v** [comment]
@ipapazov, no, all you need is HTTP access to your elasticsearch cluster. The plugin can run anywhere - on one of elasticsearch nodes, or somewhere else
