### ISSUE TITLE
The redhat package is not correct

### ISSUE THREAD

**Issue by efrangul-zz** [s12v/newrelic-elasticsearch#58]
Hi,

I took the package for RedHat at this location: https://download.newrelic.com/npi/release

I took platform_installer-linux-x86-v0.1.5.tar.gz

 ~/platform_installer_linux_x86 $ ./npi --version
./npi: bin/node: /lib/ld-linux.so.2: bad ELF interpreter: No such file or directory
~/platform_installer_linux_x86 $ 

~/platform_installer_linux_x86 $ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.3 (Maipo)
~/platform_installer_linux_x86 $

Can you generate an installer for redhat ?

Thanks.

**Comment by s12v** [comment]
@efrangul, looks like you're on a 64-bit system without 32-bit library support. Can you try `platform_installer-linux-x64-v0.1.5.tar.gz`?

**Comment by efrangul-zz** [comment]
Perfect !! ;)

~/platform_installer_linux_x64 $ ./npi --version
v0.1.5
~/platform_installer_linux_x64 $

Thanks ! ;)
