### ISSUE TITLE
Prefix cluster names

### ISSUE THREAD

**Issue by onmomo** [s12v/newrelic-elasticsearch#6]
I regard to this issue #4 . I'd like to add additional information to the _name value from elasticsearch. Like "clusterNameFromEleasticSearch-Server1234"

WDYT?

**Comment by s12v** [comment]
@onmomo, plugin reports individual nodes information as well as cluster information, so I think you don't need to specify individual servers in configuration. You only need to point it to any node of the cluster (or load balancer).

Or did I get you wrong? If so, could you provide an example of your configuration?

**Comment by onmomo** [comment]
@s12v On our dev servers, we're having multiple clusters on one machine with sometimes same node names. This would help to differentiate.

**Comment by s12v** [comment]
@onmomo, do you have different cluster names?

**Comment by s12v** [comment]
@onmomo, I mean, if you have different cluster names, they'll appear separately on the plugin page, and corresponding nodes stats will be inside of each cluster. It doesn't really matter is it shared hardware or not.
If you don't, you probably can override names with "name".
