### ISSUE TITLE
NewRelic Alerts

### ISSUE THREAD

**Issue by joshbranham** [s12v/newrelic-elasticsearch#66]
Hello,
Has anyone been able to create an alert in NewRelic based on the metric indices.merges.total_time_in_millis

I would like to monitor the time for all my clusters.

Thanks in advance,
Josh

**Comment by unicolet** [comment]
I've been trying to do the same, but for `thread_pool.search.queue` but does not work. Perhaps it's intended to be used for the *Summary metrics* only?

**Comment by joshbranham** [comment]
Yeah, I ended up using the Prometheus Exporter for Elasticsearch and derive my monitoring from there now. Closing this issue.
